### ISSUE TITLE
Media label / placeholder changes

### ISSUE THREAD

**Issue by davidheyman** [imaginerio/narratives#29]
- [x] Change media placeholder to say "Youtube, soundcloud, URL"
- [x] Change media label to "External media" and add placeholder
- [x] Change image source "Link" and add placeholder

**Comment by buccalon** [comment]
![image](https://user-images.githubusercontent.com/476699/120233109-70654780-c22b-11eb-8d34-7fbb6a061a5e.png)

Users preferred `Caption` and `Link`, instead of `Title` and `Source`.

In Portuguese `Legenda` and `Link`, instead of `Titulo` and `Fonte`.
