### ISSUE TITLE
Design sketches

### ISSUE THREAD

**Issue by buccalon** [imaginerio/narratives#33]
## Homepage
![Homepage](https://user-images.githubusercontent.com/476699/119860606-e0529580-beec-11eb-866a-ef3103c02761.png)

## Editor
![Editor](https://user-images.githubusercontent.com/476699/119860611-e21c5900-beec-11eb-9664-bfd7103538cd.png)

**Comment by davidheyman** [comment]
@bcsheesley Could you punch up these designs to get them to fit into the style of the main imagineRio website? I'd like to leave the actual editor as is but everything else is fair game, especially those cards in the map gallery on the home page. The projects here are all really excellent and I want to make sure we're showing them off the best we can.

**Comment by bcsheesley** [comment]
Here's the updated gallery page. Click the card to go directly to the narrative map. Click "Learn More" to go to a new template page for story details.

https://xd.adobe.com/view/5c90ea89-e8b8-46c4-aab6-77144f3307d3-09c3/
