### ISSUE TITLE
Admin can't add/remove narrative from gallery (keystone dashboard)

### ISSUE THREAD

**Issue by buccalon** [imaginerio/narratives#61]
![image](https://user-images.githubusercontent.com/476699/125974464-d64b4f06-4087-4292-9c50-2863c3effeec.png)

**Comment by buccalon** [comment]
@davidheyman While we don't have this fix, please publish this narrative on the gallery:
https://narratives.imaginerio.org/admin/projects/600b0120c405e1001898850c

**Comment by davidheyman** [comment]
@buccalon Can you test can confirm that this is handled by #70 as well?

**Comment by buccalon** [comment]
@davidheyman Yes, I was able to add/remove projects from the gallery using the admin panel:

![image](https://user-images.githubusercontent.com/476699/140788595-aa5cf877-a12a-426b-a397-62949481428e.png)

![image](https://user-images.githubusercontent.com/476699/140788646-41821ea9-e902-447e-8f43-ee00c65cf60c.png)
