### ISSUE TITLE
Sign up form

### ISSUE THREAD

**Issue by davidheyman** [imaginerio/narratives#66]

**Comment by davidheyman** [comment]
@buccalon What additional fields do we want to collect from users creating accounts? At the moment, I have:

1. Name*
2. Email*
3. Institution

I'm not sure if there are any other questions we'd want to ask, but let me know.

**Comment by buccalon** [comment]
This is good. I'd add two checkboxes for:

- [ ] I agree with imagineRio's [Terms of Use](https://www.imaginerio.org/terms) and [Privacy Policy](https://www.imaginerio.org/privacy)
- [ ] I want to receive emails from the imagineRio team
