### ISSUE TITLE
Locker is not saved

### ISSUE THREAD

**Issue by buccalon** [imaginerio/narratives#71]
![image](https://user-images.githubusercontent.com/476699/141322839-07549b09-6336-432a-8a9d-fa28ee0f0f31.png)

If you lock a position and refresh the editor, the locker will open. 

Users expect the locker to open only when they click the button.

**Comment by davidheyman** [comment]
I think this is behaving as designed. The position lock is a temporary editor state, not something that is saved with the slide.
